#include "ir_ac.h"

#include <IRremoteESP8266.h>
#include <IRsend.h>
#include <ir_Daikin.h>
#include <driver/rmt.h>

#include <vector>

#include "state.h"

namespace {
constexpr uint16_t kIrLed = 46; // StickS3 IR transmitter
constexpr rmt_channel_t kRmtChannel = RMT_CHANNEL_0;

// IRDaikin2 is used ONLY to build the 39-byte protocol state (getRaw()); the
// actual waveform is generated by the ESP32 RMT peripheral with hardware
// timing, so WiFi/BLE interrupts cannot corrupt it (bit-banged sends were
// unreliable with the radios up).
IRDaikin2 g_ac(kIrLed);

// Tracked locally: the IRDaikin2 vertical-swing/purify getters are awkward to
// read back, so we remember what we last set.
bool g_swing = false;
bool g_streamer = false;

// Practical temperature bounds (the protocol allows 10..32, but a room AC
// realistically runs 16..30).
constexpr int kMinTemp = 16;
constexpr int kMaxTemp = 30;

// Total frames per command; hardware timing is exact, 2 is ample margin.
constexpr int kIrSendFrames = 2;

// Appends a fixed-level duration, splitting anything over the RMT 15-bit
// per-entry limit (the 35.2 ms section gap exceeds it).
void appendDur(std::vector<std::pair<uint16_t, bool>>& v, uint32_t us, bool level) {
    while (us > 0) {
        uint16_t d = us > 30000 ? 30000 : (uint16_t)us;
        v.emplace_back(d, level);
        us -= d;
    }
}

// Daikin2 frame timing (from IRremoteESP8266 ir_Daikin): leader + 2 sections,
// bits LSB-first, 36.7 kHz carrier.
void appendSection(std::vector<std::pair<uint16_t, bool>>& v, const uint8_t* data,
                   size_t nbytes) {
    appendDur(v, kDaikin2HdrMark, true);
    appendDur(v, kDaikin2HdrSpace, false);
    for (size_t i = 0; i < nbytes; i++) {
        for (uint8_t bit = 0; bit < 8; bit++) { // LSB first
            appendDur(v, kDaikin2BitMark, true);
            appendDur(v, (data[i] >> bit) & 1 ? kDaikin2OneSpace : kDaikin2ZeroSpace, false);
        }
    }
    appendDur(v, kDaikin2BitMark, true);              // footer
    appendDur(v, (uint32_t)kDaikin2Gap, false);       // 35204 us, gets split
}

void rmtSendDaikin2(const uint8_t* data) {
    std::vector<std::pair<uint16_t, bool>> durs;
    durs.reserve(680);
    appendDur(durs, kDaikin2LeaderMark, true);
    appendDur(durs, kDaikin2LeaderSpace, false);
    appendSection(durs, data, kDaikin2Section1Length);
    appendSection(durs, data + kDaikin2Section1Length, kDaikin2Section2Length);

    // Pack duration/level pairs two-per-item.
    std::vector<rmt_item32_t> items((durs.size() + 1) / 2);
    for (size_t i = 0; i < items.size(); i++) {
        rmt_item32_t& it = items[i];
        it.duration0 = durs[2 * i].first;
        it.level0 = durs[2 * i].second;
        if (2 * i + 1 < durs.size()) {
            it.duration1 = durs[2 * i + 1].first;
            it.level1 = durs[2 * i + 1].second;
        } else {
            it.duration1 = 0;
            it.level1 = 0;
        }
    }
    rmt_write_items(kRmtChannel, items.data(), items.size(), true /*wait*/);
}
} // namespace

void ir_ac_init() {
    rmt_config_t cfg = RMT_DEFAULT_CONFIG_TX((gpio_num_t)kIrLed, kRmtChannel);
    cfg.clk_div = 80; // 80 MHz / 80 -> 1 us per tick
    cfg.tx_config.carrier_en = true;
    cfg.tx_config.carrier_freq_hz = kDaikin2Freq; // 36.7 kHz
    cfg.tx_config.carrier_duty_percent = 50;
    cfg.tx_config.carrier_level = RMT_CARRIER_LEVEL_HIGH;
    cfg.tx_config.idle_level = RMT_IDLE_LEVEL_LOW;
    cfg.tx_config.idle_output_en = true;
    esp_err_t err = rmt_config(&cfg);
    if (err == ESP_OK) err = rmt_driver_install(kRmtChannel, 0, 0);
    Serial.printf("IR: Daikin2 via RMT on pin %u: %s\n", kIrLed, esp_err_to_name(err));

    // Sensible defaults; not sent until the first real command.
    g_ac.setPower(false);
    g_ac.setMode(kDaikinCool);
    g_ac.setTemp(26);
    g_ac.setFan(kDaikinFanAuto);
}

void ir_ac_service() {
    AcCommand c = g_state.takeAcCommand();
    if (!c.pending) return;

    if (c.has_mode) g_ac.setMode(c.mode);
    if (c.has_temp) g_ac.setTemp(c.temp);
    if (c.has_fan) g_ac.setFan(c.fan);
    if (c.has_swing) {
        g_swing = c.swing;
        g_ac.setSwingVertical((uint8_t)(c.swing ? kDaikin2SwingVAuto : kDaikin2SwingVOff));
    }
    if (c.has_streamer) {
        g_streamer = c.streamer;
        g_ac.setPurify(c.streamer);
    }
    if (c.has_power) g_ac.setPower(c.power);

    const uint8_t* raw = g_ac.getRaw(); // runs the checksum
    for (int i = 0; i < kIrSendFrames; i++) rmtSendDaikin2(raw);

    AcState s;
    s.known = true;
    s.power = g_ac.getPower();
    s.mode = g_ac.getMode();
    s.temp = g_ac.getTemp();
    s.fan = g_ac.getFan();
    s.swing = g_swing;
    s.streamer = g_streamer;
    s.updatedMs = millis();
    g_state.setAcState(s);

    Serial.printf("IR: sent Daikin2 power=%d mode=%s temp=%u fan=%s swing=%d streamer=%d\n",
                  s.power, ir_ac_mode_to_string(s.mode), s.temp,
                  ir_ac_fan_to_string(s.fan), s.swing, s.streamer);
}

bool ir_ac_mode_from_string(const char* s, uint8_t* out) {
    if (!s) return false;
    if (!strcasecmp(s, "auto")) *out = kDaikinAuto;
    else if (!strcasecmp(s, "cool")) *out = kDaikinCool;
    else if (!strcasecmp(s, "heat")) *out = kDaikinHeat;
    else if (!strcasecmp(s, "dry")) *out = kDaikinDry;
    else if (!strcasecmp(s, "fan")) *out = kDaikinFan;
    else return false;
    return true;
}

const char* ir_ac_mode_to_string(uint8_t mode) {
    switch (mode) {
    case kDaikinAuto: return "auto";
    case kDaikinCool: return "cool";
    case kDaikinHeat: return "heat";
    case kDaikinDry: return "dry";
    case kDaikinFan: return "fan";
    default: return "unknown";
    }
}

bool ir_ac_fan_from_string(const char* s, uint8_t* out) {
    if (!s) return false;
    if (!strcasecmp(s, "auto")) *out = kDaikinFanAuto;
    else if (!strcasecmp(s, "quiet")) *out = kDaikinFanQuiet;
    else if (!strcasecmp(s, "low") || !strcasecmp(s, "min")) *out = kDaikinFanMin;
    else if (!strcasecmp(s, "medium") || !strcasecmp(s, "med")) *out = kDaikinFanMed;
    else if (!strcasecmp(s, "high") || !strcasecmp(s, "max")) *out = kDaikinFanMax;
    else return false;
    return true;
}

const char* ir_ac_fan_to_string(uint8_t fan) {
    switch (fan) {
    case kDaikinFanAuto: return "auto";
    case kDaikinFanQuiet: return "quiet";
    case kDaikinFanMin: return "low";
    case kDaikinFanMed: return "medium";
    case kDaikinFanMax: return "high";
    default: return "unknown";
    }
}

uint8_t ir_ac_clamp_temp(int temp) {
    if (temp < kMinTemp) temp = kMinTemp;
    if (temp > kMaxTemp) temp = kMaxTemp;
    return (uint8_t)temp;
}

AcCommand ir_ac_button_toggle() {
    AcState ac = g_state.acState();
    AcCommand cmd;
    cmd.has_power = true;
    if (ac.known && ac.power) {
        cmd.power = false; // currently on -> turn off
    } else {
        // Summer default: cool, 24 C, vertical swing.
        cmd.power = true;
        cmd.has_mode = true;
        cmd.mode = kDaikinCool;
        cmd.has_temp = true;
        cmd.temp = 24;
        cmd.has_swing = true;
        cmd.swing = true;
    }
    return cmd;
}
